fname <- paste(getwd(),"Statistical_Inference/Variance/Vform.jpeg",sep="/")
temp <- readJPEG(fname)
#img <- as.raster(temp)
plot.new()
plotArea=par('fig')
rasterImage(temp,plotArea[1],plotArea[3],plotArea[2],plotArea[4],interpolate=FALSE)
