#fname <- paste(getwd(),"Statistical_Inference/Variance/Vform.jpeg",sep="/")
fname <- pathtofile("Vform.jpeg")
try(dev.off(),silent=TRUE)
plot.new()
plotArea=par('fig')
rasterImage(readJPEG(fname),plotArea[1],plotArea[3],plotArea[2],plotArea[4],interpolate=FALSE)
