Lesson Name:  Test lesson
Course Name:  Test Video and Figure
Type:         Standard
Author:       Your name goes here
Organization: The name of your organization goes here (optional)
Version:      2.1.1
================================================================

--- &text

This is a block of text, denoted above by "--- &text". Blocks of text will be displayed to the user and do not require any input other than pressing Return to continue to the next block.

--- &figure

Here is a boxplot.

*** .figure
mod1_boxplot.R

*** .fig_type
new

--- &video

Here is a video.

*** .video_url
http://swirlstats.com

--- &cmd_question

This is a command question, denoted above by "--- &cmd_question". Command questions require the user to enter a valid R expression at the prompt. As an example, let's have the user store the result of `3 + 7` in a new variable called `z`.

```{r}
z <- 3 + 7
```

*** .hint
This is a hint, which the user will see if he or she answers the question incorrectly. In this case, we might be kind and suggest that they type `z <- 3 + 7`.

--- &mult_question

This is a multiple choice question, denoted by "--- &mult_question". Here we might ask which function can be used to compute the sum of 2 or more numbers.

_1. `sum()`_
2. `mean()`
3. `abs()`

*** .hint
This is a hint, which will be displayed after an incorrect response to the question. In this example, we could tell the user that the function name is synonymous with "addition".
